/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d7dbd7',
        'surface-container': '#ebefeb',
        'surface-container-low': '#f1f4f1',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e5e9e5',
        'surface-container-highest': '#e0e3e0',
        'surface-bright': '#f7faf6',
        surface: '#f7faf6',
        'surface-variant': '#e0e3e0',
        background: '#f7faf6',
        'on-background': '#181d1a',
        'on-surface': '#181d1a',
        'on-surface-variant': '#3f4945',
        outline: '#6f7a74',
        'outline-variant': '#bec9c2',
        primary: '#005440',
        'on-primary': '#ffffff',
        'primary-container': '#0f6e56',
        'on-primary-container': '#9aedcf',
        'on-primary-fixed-variant': '#00513e',
        'primary-fixed': '#9aedcf',
        'inverse-primary': '#84d6b9',
        secondary: '#885200',
        'on-secondary-container': '#704200',
        'secondary-container': '#fdad4e',
        'secondary-fixed': '#ffdcbb',
        'secondary-fixed-dim': '#ffb869',
        'on-secondary-fixed': '#2b1700',
        'on-secondary-fixed-variant': '#673d00',
        tertiary: '#78352b',
        'tertiary-container': '#954c41',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffd3cc',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a8',
        'on-tertiary-fixed': '#3b0804',
        'on-tertiary-fixed-variant': '#743329',
        'error-container': '#ffdad6',
        accent: '#BA7517',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '80px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg': ['Tajawal', 'sans-serif'],
        'display-md': ['Tajawal', 'sans-serif'],
        'heading-sm': ['Tajawal', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        tajawal: ['Tajawal', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '1.1', fontWeight: '700' }],
        'display-md': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'heading-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
